/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ComposerRouteImport } from './routes/composer'
import { Route as CompetitorsRouteImport } from './routes/competitors'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompetitorsIndexRouteImport } from './routes/competitors.index'
import { Route as AdsIndexRouteImport } from './routes/ads.index'
import { Route as CompetitorsIdRouteImport } from './routes/competitors.$id'
import { Route as AdsGoogleRouteImport } from './routes/ads.google'
import { Route as AdsCompareRouteImport } from './routes/ads.compare'
import { Route as AdsPlatformRouteImport } from './routes/ads.$platform'
import { Route as AdsGoogleIndexRouteImport } from './routes/ads.google.index'
import { Route as AdsGoogleStatsRouteImport } from './routes/ads.google.stats'
import { Route as AdsGoogleNewRouteImport } from './routes/ads.google.new'
import { Route as AdsGoogleCampaignIdRouteImport } from './routes/ads.google.$campaignId'

const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposerRoute = ComposerRouteImport.update({
  id: '/composer',
  path: '/composer',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsRoute = CompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsIndexRoute = CompetitorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompetitorsRoute,
} as any)
const AdsIndexRoute = AdsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdsRoute,
} as any)
const CompetitorsIdRoute = CompetitorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompetitorsRoute,
} as any)
const AdsGoogleRoute = AdsGoogleRouteImport.update({
  id: '/google',
  path: '/google',
  getParentRoute: () => AdsRoute,
} as any)
const AdsCompareRoute = AdsCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AdsRoute,
} as any)
const AdsPlatformRoute = AdsPlatformRouteImport.update({
  id: '/$platform',
  path: '/$platform',
  getParentRoute: () => AdsRoute,
} as any)
const AdsGoogleIndexRoute = AdsGoogleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdsGoogleRoute,
} as any)
const AdsGoogleStatsRoute = AdsGoogleStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdsGoogleRoute,
} as any)
const AdsGoogleNewRoute = AdsGoogleNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdsGoogleRoute,
} as any)
const AdsGoogleCampaignIdRoute = AdsGoogleCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => AdsGoogleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/competitors': typeof CompetitorsRouteWithChildren
  '/composer': typeof ComposerRoute
  '/inbox': typeof InboxRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/trends': typeof TrendsRoute
  '/ads/$platform': typeof AdsPlatformRoute
  '/ads/compare': typeof AdsCompareRoute
  '/ads/google': typeof AdsGoogleRouteWithChildren
  '/competitors/$id': typeof CompetitorsIdRoute
  '/ads/': typeof AdsIndexRoute
  '/competitors/': typeof CompetitorsIndexRoute
  '/ads/google/$campaignId': typeof AdsGoogleCampaignIdRoute
  '/ads/google/new': typeof AdsGoogleNewRoute
  '/ads/google/stats': typeof AdsGoogleStatsRoute
  '/ads/google/': typeof AdsGoogleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/composer': typeof ComposerRoute
  '/inbox': typeof InboxRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/trends': typeof TrendsRoute
  '/ads/$platform': typeof AdsPlatformRoute
  '/ads/compare': typeof AdsCompareRoute
  '/competitors/$id': typeof CompetitorsIdRoute
  '/ads': typeof AdsIndexRoute
  '/competitors': typeof CompetitorsIndexRoute
  '/ads/google/$campaignId': typeof AdsGoogleCampaignIdRoute
  '/ads/google/new': typeof AdsGoogleNewRoute
  '/ads/google/stats': typeof AdsGoogleStatsRoute
  '/ads/google': typeof AdsGoogleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/competitors': typeof CompetitorsRouteWithChildren
  '/composer': typeof ComposerRoute
  '/inbox': typeof InboxRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/trends': typeof TrendsRoute
  '/ads/$platform': typeof AdsPlatformRoute
  '/ads/compare': typeof AdsCompareRoute
  '/ads/google': typeof AdsGoogleRouteWithChildren
  '/competitors/$id': typeof CompetitorsIdRoute
  '/ads/': typeof AdsIndexRoute
  '/competitors/': typeof CompetitorsIndexRoute
  '/ads/google/$campaignId': typeof AdsGoogleCampaignIdRoute
  '/ads/google/new': typeof AdsGoogleNewRoute
  '/ads/google/stats': typeof AdsGoogleStatsRoute
  '/ads/google/': typeof AdsGoogleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/calendar'
    | '/competitors'
    | '/composer'
    | '/inbox'
    | '/schedule'
    | '/settings'
    | '/trends'
    | '/ads/$platform'
    | '/ads/compare'
    | '/ads/google'
    | '/competitors/$id'
    | '/ads/'
    | '/competitors/'
    | '/ads/google/$campaignId'
    | '/ads/google/new'
    | '/ads/google/stats'
    | '/ads/google/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/composer'
    | '/inbox'
    | '/schedule'
    | '/settings'
    | '/trends'
    | '/ads/$platform'
    | '/ads/compare'
    | '/competitors/$id'
    | '/ads'
    | '/competitors'
    | '/ads/google/$campaignId'
    | '/ads/google/new'
    | '/ads/google/stats'
    | '/ads/google'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/calendar'
    | '/competitors'
    | '/composer'
    | '/inbox'
    | '/schedule'
    | '/settings'
    | '/trends'
    | '/ads/$platform'
    | '/ads/compare'
    | '/ads/google'
    | '/competitors/$id'
    | '/ads/'
    | '/competitors/'
    | '/ads/google/$campaignId'
    | '/ads/google/new'
    | '/ads/google/stats'
    | '/ads/google/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  CompetitorsRoute: typeof CompetitorsRouteWithChildren
  ComposerRoute: typeof ComposerRoute
  InboxRoute: typeof InboxRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  TrendsRoute: typeof TrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composer': {
      id: '/composer'
      path: '/composer'
      fullPath: '/composer'
      preLoaderRoute: typeof ComposerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors': {
      id: '/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof CompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors/': {
      id: '/competitors/'
      path: '/'
      fullPath: '/competitors/'
      preLoaderRoute: typeof CompetitorsIndexRouteImport
      parentRoute: typeof CompetitorsRoute
    }
    '/ads/': {
      id: '/ads/'
      path: '/'
      fullPath: '/ads/'
      preLoaderRoute: typeof AdsIndexRouteImport
      parentRoute: typeof AdsRoute
    }
    '/competitors/$id': {
      id: '/competitors/$id'
      path: '/$id'
      fullPath: '/competitors/$id'
      preLoaderRoute: typeof CompetitorsIdRouteImport
      parentRoute: typeof CompetitorsRoute
    }
    '/ads/google': {
      id: '/ads/google'
      path: '/google'
      fullPath: '/ads/google'
      preLoaderRoute: typeof AdsGoogleRouteImport
      parentRoute: typeof AdsRoute
    }
    '/ads/compare': {
      id: '/ads/compare'
      path: '/compare'
      fullPath: '/ads/compare'
      preLoaderRoute: typeof AdsCompareRouteImport
      parentRoute: typeof AdsRoute
    }
    '/ads/$platform': {
      id: '/ads/$platform'
      path: '/$platform'
      fullPath: '/ads/$platform'
      preLoaderRoute: typeof AdsPlatformRouteImport
      parentRoute: typeof AdsRoute
    }
    '/ads/google/': {
      id: '/ads/google/'
      path: '/'
      fullPath: '/ads/google/'
      preLoaderRoute: typeof AdsGoogleIndexRouteImport
      parentRoute: typeof AdsGoogleRoute
    }
    '/ads/google/stats': {
      id: '/ads/google/stats'
      path: '/stats'
      fullPath: '/ads/google/stats'
      preLoaderRoute: typeof AdsGoogleStatsRouteImport
      parentRoute: typeof AdsGoogleRoute
    }
    '/ads/google/new': {
      id: '/ads/google/new'
      path: '/new'
      fullPath: '/ads/google/new'
      preLoaderRoute: typeof AdsGoogleNewRouteImport
      parentRoute: typeof AdsGoogleRoute
    }
    '/ads/google/$campaignId': {
      id: '/ads/google/$campaignId'
      path: '/$campaignId'
      fullPath: '/ads/google/$campaignId'
      preLoaderRoute: typeof AdsGoogleCampaignIdRouteImport
      parentRoute: typeof AdsGoogleRoute
    }
  }
}

interface AdsGoogleRouteChildren {
  AdsGoogleCampaignIdRoute: typeof AdsGoogleCampaignIdRoute
  AdsGoogleNewRoute: typeof AdsGoogleNewRoute
  AdsGoogleStatsRoute: typeof AdsGoogleStatsRoute
  AdsGoogleIndexRoute: typeof AdsGoogleIndexRoute
}

const AdsGoogleRouteChildren: AdsGoogleRouteChildren = {
  AdsGoogleCampaignIdRoute: AdsGoogleCampaignIdRoute,
  AdsGoogleNewRoute: AdsGoogleNewRoute,
  AdsGoogleStatsRoute: AdsGoogleStatsRoute,
  AdsGoogleIndexRoute: AdsGoogleIndexRoute,
}

const AdsGoogleRouteWithChildren = AdsGoogleRoute._addFileChildren(
  AdsGoogleRouteChildren,
)

interface AdsRouteChildren {
  AdsPlatformRoute: typeof AdsPlatformRoute
  AdsCompareRoute: typeof AdsCompareRoute
  AdsGoogleRoute: typeof AdsGoogleRouteWithChildren
  AdsIndexRoute: typeof AdsIndexRoute
}

const AdsRouteChildren: AdsRouteChildren = {
  AdsPlatformRoute: AdsPlatformRoute,
  AdsCompareRoute: AdsCompareRoute,
  AdsGoogleRoute: AdsGoogleRouteWithChildren,
  AdsIndexRoute: AdsIndexRoute,
}

const AdsRouteWithChildren = AdsRoute._addFileChildren(AdsRouteChildren)

interface CompetitorsRouteChildren {
  CompetitorsIdRoute: typeof CompetitorsIdRoute
  CompetitorsIndexRoute: typeof CompetitorsIndexRoute
}

const CompetitorsRouteChildren: CompetitorsRouteChildren = {
  CompetitorsIdRoute: CompetitorsIdRoute,
  CompetitorsIndexRoute: CompetitorsIndexRoute,
}

const CompetitorsRouteWithChildren = CompetitorsRoute._addFileChildren(
  CompetitorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRouteWithChildren,
  CalendarRoute: CalendarRoute,
  CompetitorsRoute: CompetitorsRouteWithChildren,
  ComposerRoute: ComposerRoute,
  InboxRoute: InboxRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  TrendsRoute: TrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
