/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as MetaRouteImport } from './routes/meta'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ComposerRouteImport } from './routes/composer'
import { Route as CompetitorsRouteImport } from './routes/competitors'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LandingpagesIndexRouteImport } from './routes/landingpages.index'
import { Route as CompetitorsIndexRouteImport } from './routes/competitors.index'
import { Route as AdsIndexRouteImport } from './routes/ads.index'
import { Route as OfferteSlugRouteImport } from './routes/offerte.$slug'
import { Route as LeadsFunnelsRouteImport } from './routes/leads.funnels'
import { Route as LeadsBranchesRouteImport } from './routes/leads.branches'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'
import { Route as LandingpagesIdRouteImport } from './routes/landingpages.$id'
import { Route as LandingAiIdRouteImport } from './routes/landing-ai.$id'
import { Route as CompetitorsIdRouteImport } from './routes/competitors.$id'
import { Route as CadeauplatformSlugRouteImport } from './routes/cadeauplatform.$slug'
import { Route as AdsGoogleRouteImport } from './routes/ads.google'
import { Route as AdsCompareRouteImport } from './routes/ads.compare'
import { Route as AdsPlatformRouteImport } from './routes/ads.$platform'
import { Route as AdsGoogleIndexRouteImport } from './routes/ads.google.index'
import { Route as ApiPublicMetaCallbackRouteImport } from './routes/api/public/meta-callback'
import { Route as ApiPublicLeadStatusRouteImport } from './routes/api/public/lead-status'
import { Route as AdsGoogleStatsRouteImport } from './routes/ads.google.stats'
import { Route as AdsGoogleNewRouteImport } from './routes/ads.google.new'
import { Route as AdsGoogleConversionsRouteImport } from './routes/ads.google.conversions'
import { Route as AdsGoogleAdviceRouteImport } from './routes/ads.google.advice'
import { Route as AdsGoogleCampaignIdRouteImport } from './routes/ads.google.$campaignId'
import { Route as ApiPublicLeadIngestQuoteRouteImport } from './routes/api/public/lead-ingest.quote'
import { Route as ApiPublicLeadIngestPlatformRouteImport } from './routes/api/public/lead-ingest.platform'

const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaRoute = MetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposerRoute = ComposerRouteImport.update({
  id: '/composer',
  path: '/composer',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsRoute = CompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeadsRoute,
} as any)
const LandingpagesIndexRoute = LandingpagesIndexRouteImport.update({
  id: '/landingpages/',
  path: '/landingpages/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsIndexRoute = CompetitorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompetitorsRoute,
} as any)
const AdsIndexRoute = AdsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdsRoute,
} as any)
const OfferteSlugRoute = OfferteSlugRouteImport.update({
  id: '/offerte/$slug',
  path: '/offerte/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsFunnelsRoute = LeadsFunnelsRouteImport.update({
  id: '/funnels',
  path: '/funnels',
  getParentRoute: () => LeadsRoute,
} as any)
const LeadsBranchesRoute = LeadsBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => LeadsRoute,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LeadsRoute,
} as any)
const LandingpagesIdRoute = LandingpagesIdRouteImport.update({
  id: '/landingpages/$id',
  path: '/landingpages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingAiIdRoute = LandingAiIdRouteImport.update({
  id: '/landing-ai/$id',
  path: '/landing-ai/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsIdRoute = CompetitorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompetitorsRoute,
} as any)
const CadeauplatformSlugRoute = CadeauplatformSlugRouteImport.update({
  id: '/cadeauplatform/$slug',
  path: '/cadeauplatform/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsGoogleRoute = AdsGoogleRouteImport.update({
  id: '/google',
  path: '/google',
  getParentRoute: () => AdsRoute,
} as any)
const AdsCompareRoute = AdsCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AdsRoute,
} as any)
const AdsPlatformRoute = AdsPlatformRouteImport.update({
  id: '/$platform',
  path: '/$platform',
  getParentRoute: () => AdsRoute,
} as any)
const AdsGoogleIndexRoute = AdsGoogleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdsGoogleRoute,
} as any)
const ApiPublicMetaCallbackRoute = ApiPublicMetaCallbackRouteImport.update({
  id: '/api/public/meta-callback',
  path: '/api/public/meta-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadStatusRoute = ApiPublicLeadStatusRouteImport.update({
  id: '/api/public/lead-status',
  path: '/api/public/lead-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsGoogleStatsRoute = AdsGoogleStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdsGoogleRoute,
} as any)
const AdsGoogleNewRoute = AdsGoogleNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdsGoogleRoute,
} as any)
const AdsGoogleConversionsRoute = AdsGoogleConversionsRouteImport.update({
  id: '/conversions',
  path: '/conversions',
  getParentRoute: () => AdsGoogleRoute,
} as any)
const AdsGoogleAdviceRoute = AdsGoogleAdviceRouteImport.update({
  id: '/advice',
  path: '/advice',
  getParentRoute: () => AdsGoogleRoute,
} as any)
const AdsGoogleCampaignIdRoute = AdsGoogleCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => AdsGoogleRoute,
} as any)
const ApiPublicLeadIngestQuoteRoute =
  ApiPublicLeadIngestQuoteRouteImport.update({
    id: '/api/public/lead-ingest/quote',
    path: '/api/public/lead-ingest/quote',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadIngestPlatformRoute =
  ApiPublicLeadIngestPlatformRouteImport.update({
    id: '/api/public/lead-ingest/platform',
    path: '/api/public/lead-ingest/platform',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/competitors': typeof CompetitorsRouteWithChildren
  '/composer': typeof ComposerRoute
  '/inbox': typeof InboxRoute
  '/leads': typeof LeadsRouteWithChildren
  '/meta': typeof MetaRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trends': typeof TrendsRoute
  '/ads/$platform': typeof AdsPlatformRoute
  '/ads/compare': typeof AdsCompareRoute
  '/ads/google': typeof AdsGoogleRouteWithChildren
  '/cadeauplatform/$slug': typeof CadeauplatformSlugRoute
  '/competitors/$id': typeof CompetitorsIdRoute
  '/landing-ai/$id': typeof LandingAiIdRoute
  '/landingpages/$id': typeof LandingpagesIdRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/branches': typeof LeadsBranchesRoute
  '/leads/funnels': typeof LeadsFunnelsRoute
  '/offerte/$slug': typeof OfferteSlugRoute
  '/ads/': typeof AdsIndexRoute
  '/competitors/': typeof CompetitorsIndexRoute
  '/landingpages/': typeof LandingpagesIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/ads/google/$campaignId': typeof AdsGoogleCampaignIdRoute
  '/ads/google/advice': typeof AdsGoogleAdviceRoute
  '/ads/google/conversions': typeof AdsGoogleConversionsRoute
  '/ads/google/new': typeof AdsGoogleNewRoute
  '/ads/google/stats': typeof AdsGoogleStatsRoute
  '/api/public/lead-status': typeof ApiPublicLeadStatusRoute
  '/api/public/meta-callback': typeof ApiPublicMetaCallbackRoute
  '/ads/google/': typeof AdsGoogleIndexRoute
  '/api/public/lead-ingest/platform': typeof ApiPublicLeadIngestPlatformRoute
  '/api/public/lead-ingest/quote': typeof ApiPublicLeadIngestQuoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/composer': typeof ComposerRoute
  '/inbox': typeof InboxRoute
  '/meta': typeof MetaRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trends': typeof TrendsRoute
  '/ads/$platform': typeof AdsPlatformRoute
  '/ads/compare': typeof AdsCompareRoute
  '/cadeauplatform/$slug': typeof CadeauplatformSlugRoute
  '/competitors/$id': typeof CompetitorsIdRoute
  '/landing-ai/$id': typeof LandingAiIdRoute
  '/landingpages/$id': typeof LandingpagesIdRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/branches': typeof LeadsBranchesRoute
  '/leads/funnels': typeof LeadsFunnelsRoute
  '/offerte/$slug': typeof OfferteSlugRoute
  '/ads': typeof AdsIndexRoute
  '/competitors': typeof CompetitorsIndexRoute
  '/landingpages': typeof LandingpagesIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/ads/google/$campaignId': typeof AdsGoogleCampaignIdRoute
  '/ads/google/advice': typeof AdsGoogleAdviceRoute
  '/ads/google/conversions': typeof AdsGoogleConversionsRoute
  '/ads/google/new': typeof AdsGoogleNewRoute
  '/ads/google/stats': typeof AdsGoogleStatsRoute
  '/api/public/lead-status': typeof ApiPublicLeadStatusRoute
  '/api/public/meta-callback': typeof ApiPublicMetaCallbackRoute
  '/ads/google': typeof AdsGoogleIndexRoute
  '/api/public/lead-ingest/platform': typeof ApiPublicLeadIngestPlatformRoute
  '/api/public/lead-ingest/quote': typeof ApiPublicLeadIngestQuoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/competitors': typeof CompetitorsRouteWithChildren
  '/composer': typeof ComposerRoute
  '/inbox': typeof InboxRoute
  '/leads': typeof LeadsRouteWithChildren
  '/meta': typeof MetaRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trends': typeof TrendsRoute
  '/ads/$platform': typeof AdsPlatformRoute
  '/ads/compare': typeof AdsCompareRoute
  '/ads/google': typeof AdsGoogleRouteWithChildren
  '/cadeauplatform/$slug': typeof CadeauplatformSlugRoute
  '/competitors/$id': typeof CompetitorsIdRoute
  '/landing-ai/$id': typeof LandingAiIdRoute
  '/landingpages/$id': typeof LandingpagesIdRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/branches': typeof LeadsBranchesRoute
  '/leads/funnels': typeof LeadsFunnelsRoute
  '/offerte/$slug': typeof OfferteSlugRoute
  '/ads/': typeof AdsIndexRoute
  '/competitors/': typeof CompetitorsIndexRoute
  '/landingpages/': typeof LandingpagesIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/ads/google/$campaignId': typeof AdsGoogleCampaignIdRoute
  '/ads/google/advice': typeof AdsGoogleAdviceRoute
  '/ads/google/conversions': typeof AdsGoogleConversionsRoute
  '/ads/google/new': typeof AdsGoogleNewRoute
  '/ads/google/stats': typeof AdsGoogleStatsRoute
  '/api/public/lead-status': typeof ApiPublicLeadStatusRoute
  '/api/public/meta-callback': typeof ApiPublicMetaCallbackRoute
  '/ads/google/': typeof AdsGoogleIndexRoute
  '/api/public/lead-ingest/platform': typeof ApiPublicLeadIngestPlatformRoute
  '/api/public/lead-ingest/quote': typeof ApiPublicLeadIngestQuoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/calendar'
    | '/competitors'
    | '/composer'
    | '/inbox'
    | '/leads'
    | '/meta'
    | '/schedule'
    | '/settings'
    | '/sitemap.xml'
    | '/trends'
    | '/ads/$platform'
    | '/ads/compare'
    | '/ads/google'
    | '/cadeauplatform/$slug'
    | '/competitors/$id'
    | '/landing-ai/$id'
    | '/landingpages/$id'
    | '/leads/$id'
    | '/leads/branches'
    | '/leads/funnels'
    | '/offerte/$slug'
    | '/ads/'
    | '/competitors/'
    | '/landingpages/'
    | '/leads/'
    | '/ads/google/$campaignId'
    | '/ads/google/advice'
    | '/ads/google/conversions'
    | '/ads/google/new'
    | '/ads/google/stats'
    | '/api/public/lead-status'
    | '/api/public/meta-callback'
    | '/ads/google/'
    | '/api/public/lead-ingest/platform'
    | '/api/public/lead-ingest/quote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/composer'
    | '/inbox'
    | '/meta'
    | '/schedule'
    | '/settings'
    | '/sitemap.xml'
    | '/trends'
    | '/ads/$platform'
    | '/ads/compare'
    | '/cadeauplatform/$slug'
    | '/competitors/$id'
    | '/landing-ai/$id'
    | '/landingpages/$id'
    | '/leads/$id'
    | '/leads/branches'
    | '/leads/funnels'
    | '/offerte/$slug'
    | '/ads'
    | '/competitors'
    | '/landingpages'
    | '/leads'
    | '/ads/google/$campaignId'
    | '/ads/google/advice'
    | '/ads/google/conversions'
    | '/ads/google/new'
    | '/ads/google/stats'
    | '/api/public/lead-status'
    | '/api/public/meta-callback'
    | '/ads/google'
    | '/api/public/lead-ingest/platform'
    | '/api/public/lead-ingest/quote'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/calendar'
    | '/competitors'
    | '/composer'
    | '/inbox'
    | '/leads'
    | '/meta'
    | '/schedule'
    | '/settings'
    | '/sitemap.xml'
    | '/trends'
    | '/ads/$platform'
    | '/ads/compare'
    | '/ads/google'
    | '/cadeauplatform/$slug'
    | '/competitors/$id'
    | '/landing-ai/$id'
    | '/landingpages/$id'
    | '/leads/$id'
    | '/leads/branches'
    | '/leads/funnels'
    | '/offerte/$slug'
    | '/ads/'
    | '/competitors/'
    | '/landingpages/'
    | '/leads/'
    | '/ads/google/$campaignId'
    | '/ads/google/advice'
    | '/ads/google/conversions'
    | '/ads/google/new'
    | '/ads/google/stats'
    | '/api/public/lead-status'
    | '/api/public/meta-callback'
    | '/ads/google/'
    | '/api/public/lead-ingest/platform'
    | '/api/public/lead-ingest/quote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  CompetitorsRoute: typeof CompetitorsRouteWithChildren
  ComposerRoute: typeof ComposerRoute
  InboxRoute: typeof InboxRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  MetaRoute: typeof MetaRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrendsRoute: typeof TrendsRoute
  CadeauplatformSlugRoute: typeof CadeauplatformSlugRoute
  LandingAiIdRoute: typeof LandingAiIdRoute
  LandingpagesIdRoute: typeof LandingpagesIdRoute
  OfferteSlugRoute: typeof OfferteSlugRoute
  LandingpagesIndexRoute: typeof LandingpagesIndexRoute
  ApiPublicLeadStatusRoute: typeof ApiPublicLeadStatusRoute
  ApiPublicMetaCallbackRoute: typeof ApiPublicMetaCallbackRoute
  ApiPublicLeadIngestPlatformRoute: typeof ApiPublicLeadIngestPlatformRoute
  ApiPublicLeadIngestQuoteRoute: typeof ApiPublicLeadIngestQuoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta': {
      id: '/meta'
      path: '/meta'
      fullPath: '/meta'
      preLoaderRoute: typeof MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composer': {
      id: '/composer'
      path: '/composer'
      fullPath: '/composer'
      preLoaderRoute: typeof ComposerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors': {
      id: '/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof CompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/landingpages/': {
      id: '/landingpages/'
      path: '/landingpages'
      fullPath: '/landingpages/'
      preLoaderRoute: typeof LandingpagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors/': {
      id: '/competitors/'
      path: '/'
      fullPath: '/competitors/'
      preLoaderRoute: typeof CompetitorsIndexRouteImport
      parentRoute: typeof CompetitorsRoute
    }
    '/ads/': {
      id: '/ads/'
      path: '/'
      fullPath: '/ads/'
      preLoaderRoute: typeof AdsIndexRouteImport
      parentRoute: typeof AdsRoute
    }
    '/offerte/$slug': {
      id: '/offerte/$slug'
      path: '/offerte/$slug'
      fullPath: '/offerte/$slug'
      preLoaderRoute: typeof OfferteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/funnels': {
      id: '/leads/funnels'
      path: '/funnels'
      fullPath: '/leads/funnels'
      preLoaderRoute: typeof LeadsFunnelsRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/leads/branches': {
      id: '/leads/branches'
      path: '/branches'
      fullPath: '/leads/branches'
      preLoaderRoute: typeof LeadsBranchesRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/landingpages/$id': {
      id: '/landingpages/$id'
      path: '/landingpages/$id'
      fullPath: '/landingpages/$id'
      preLoaderRoute: typeof LandingpagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-ai/$id': {
      id: '/landing-ai/$id'
      path: '/landing-ai/$id'
      fullPath: '/landing-ai/$id'
      preLoaderRoute: typeof LandingAiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors/$id': {
      id: '/competitors/$id'
      path: '/$id'
      fullPath: '/competitors/$id'
      preLoaderRoute: typeof CompetitorsIdRouteImport
      parentRoute: typeof CompetitorsRoute
    }
    '/cadeauplatform/$slug': {
      id: '/cadeauplatform/$slug'
      path: '/cadeauplatform/$slug'
      fullPath: '/cadeauplatform/$slug'
      preLoaderRoute: typeof CadeauplatformSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/google': {
      id: '/ads/google'
      path: '/google'
      fullPath: '/ads/google'
      preLoaderRoute: typeof AdsGoogleRouteImport
      parentRoute: typeof AdsRoute
    }
    '/ads/compare': {
      id: '/ads/compare'
      path: '/compare'
      fullPath: '/ads/compare'
      preLoaderRoute: typeof AdsCompareRouteImport
      parentRoute: typeof AdsRoute
    }
    '/ads/$platform': {
      id: '/ads/$platform'
      path: '/$platform'
      fullPath: '/ads/$platform'
      preLoaderRoute: typeof AdsPlatformRouteImport
      parentRoute: typeof AdsRoute
    }
    '/ads/google/': {
      id: '/ads/google/'
      path: '/'
      fullPath: '/ads/google/'
      preLoaderRoute: typeof AdsGoogleIndexRouteImport
      parentRoute: typeof AdsGoogleRoute
    }
    '/api/public/meta-callback': {
      id: '/api/public/meta-callback'
      path: '/api/public/meta-callback'
      fullPath: '/api/public/meta-callback'
      preLoaderRoute: typeof ApiPublicMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-status': {
      id: '/api/public/lead-status'
      path: '/api/public/lead-status'
      fullPath: '/api/public/lead-status'
      preLoaderRoute: typeof ApiPublicLeadStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/google/stats': {
      id: '/ads/google/stats'
      path: '/stats'
      fullPath: '/ads/google/stats'
      preLoaderRoute: typeof AdsGoogleStatsRouteImport
      parentRoute: typeof AdsGoogleRoute
    }
    '/ads/google/new': {
      id: '/ads/google/new'
      path: '/new'
      fullPath: '/ads/google/new'
      preLoaderRoute: typeof AdsGoogleNewRouteImport
      parentRoute: typeof AdsGoogleRoute
    }
    '/ads/google/conversions': {
      id: '/ads/google/conversions'
      path: '/conversions'
      fullPath: '/ads/google/conversions'
      preLoaderRoute: typeof AdsGoogleConversionsRouteImport
      parentRoute: typeof AdsGoogleRoute
    }
    '/ads/google/advice': {
      id: '/ads/google/advice'
      path: '/advice'
      fullPath: '/ads/google/advice'
      preLoaderRoute: typeof AdsGoogleAdviceRouteImport
      parentRoute: typeof AdsGoogleRoute
    }
    '/ads/google/$campaignId': {
      id: '/ads/google/$campaignId'
      path: '/$campaignId'
      fullPath: '/ads/google/$campaignId'
      preLoaderRoute: typeof AdsGoogleCampaignIdRouteImport
      parentRoute: typeof AdsGoogleRoute
    }
    '/api/public/lead-ingest/quote': {
      id: '/api/public/lead-ingest/quote'
      path: '/api/public/lead-ingest/quote'
      fullPath: '/api/public/lead-ingest/quote'
      preLoaderRoute: typeof ApiPublicLeadIngestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-ingest/platform': {
      id: '/api/public/lead-ingest/platform'
      path: '/api/public/lead-ingest/platform'
      fullPath: '/api/public/lead-ingest/platform'
      preLoaderRoute: typeof ApiPublicLeadIngestPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdsGoogleRouteChildren {
  AdsGoogleCampaignIdRoute: typeof AdsGoogleCampaignIdRoute
  AdsGoogleAdviceRoute: typeof AdsGoogleAdviceRoute
  AdsGoogleConversionsRoute: typeof AdsGoogleConversionsRoute
  AdsGoogleNewRoute: typeof AdsGoogleNewRoute
  AdsGoogleStatsRoute: typeof AdsGoogleStatsRoute
  AdsGoogleIndexRoute: typeof AdsGoogleIndexRoute
}

const AdsGoogleRouteChildren: AdsGoogleRouteChildren = {
  AdsGoogleCampaignIdRoute: AdsGoogleCampaignIdRoute,
  AdsGoogleAdviceRoute: AdsGoogleAdviceRoute,
  AdsGoogleConversionsRoute: AdsGoogleConversionsRoute,
  AdsGoogleNewRoute: AdsGoogleNewRoute,
  AdsGoogleStatsRoute: AdsGoogleStatsRoute,
  AdsGoogleIndexRoute: AdsGoogleIndexRoute,
}

const AdsGoogleRouteWithChildren = AdsGoogleRoute._addFileChildren(
  AdsGoogleRouteChildren,
)

interface AdsRouteChildren {
  AdsPlatformRoute: typeof AdsPlatformRoute
  AdsCompareRoute: typeof AdsCompareRoute
  AdsGoogleRoute: typeof AdsGoogleRouteWithChildren
  AdsIndexRoute: typeof AdsIndexRoute
}

const AdsRouteChildren: AdsRouteChildren = {
  AdsPlatformRoute: AdsPlatformRoute,
  AdsCompareRoute: AdsCompareRoute,
  AdsGoogleRoute: AdsGoogleRouteWithChildren,
  AdsIndexRoute: AdsIndexRoute,
}

const AdsRouteWithChildren = AdsRoute._addFileChildren(AdsRouteChildren)

interface CompetitorsRouteChildren {
  CompetitorsIdRoute: typeof CompetitorsIdRoute
  CompetitorsIndexRoute: typeof CompetitorsIndexRoute
}

const CompetitorsRouteChildren: CompetitorsRouteChildren = {
  CompetitorsIdRoute: CompetitorsIdRoute,
  CompetitorsIndexRoute: CompetitorsIndexRoute,
}

const CompetitorsRouteWithChildren = CompetitorsRoute._addFileChildren(
  CompetitorsRouteChildren,
)

interface LeadsRouteChildren {
  LeadsIdRoute: typeof LeadsIdRoute
  LeadsBranchesRoute: typeof LeadsBranchesRoute
  LeadsFunnelsRoute: typeof LeadsFunnelsRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsIdRoute: LeadsIdRoute,
  LeadsBranchesRoute: LeadsBranchesRoute,
  LeadsFunnelsRoute: LeadsFunnelsRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRouteWithChildren,
  CalendarRoute: CalendarRoute,
  CompetitorsRoute: CompetitorsRouteWithChildren,
  ComposerRoute: ComposerRoute,
  InboxRoute: InboxRoute,
  LeadsRoute: LeadsRouteWithChildren,
  MetaRoute: MetaRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrendsRoute: TrendsRoute,
  CadeauplatformSlugRoute: CadeauplatformSlugRoute,
  LandingAiIdRoute: LandingAiIdRoute,
  LandingpagesIdRoute: LandingpagesIdRoute,
  OfferteSlugRoute: OfferteSlugRoute,
  LandingpagesIndexRoute: LandingpagesIndexRoute,
  ApiPublicLeadStatusRoute: ApiPublicLeadStatusRoute,
  ApiPublicMetaCallbackRoute: ApiPublicMetaCallbackRoute,
  ApiPublicLeadIngestPlatformRoute: ApiPublicLeadIngestPlatformRoute,
  ApiPublicLeadIngestQuoteRoute: ApiPublicLeadIngestQuoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
